### ISSUE TITLE
Range map incorrect

### ISSUE THREAD

**Issue by mjb1416** [MattCheetham/zeddy-support#12]
The range map and it does not look right. I think it’s treating my range in miles as if it were kilometres.

**To Reproduce**
Make a note of current range in miles 
View the range map
Compare distance to town near boundary using Google maps
Distance is roughly your range but in kilometres rather than miles

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
13.5.1

**Zeddy version**: Version of Zeddy this bug occurred on (can be found in Zeddy's Settings tab)
2.1.1 (18)
**iOS device**: For example iPhone XS, iPad mini, etc.
iPhone 7
**Reproducible:** Can you reproduce it every time? Or is it random?
Every time
**Expected behavior**

Map should display locations range miles away

**Screenshots**
If possible, add screenshots to help show the problem.
Can’t paste here from phone, but range currently 175 miles. Map ends at Kenilworth which is 118 miles away. 118 miles is  189 km which is close to my range in miles. 

**Additional context**

**Comment by MattCheetham** [comment]
@mjb1416 Thanks for this detailed report. Can you confirm if you see the same range map bug in the My Renault app? You can view it by clicking on the map tap and pressing the little map pin icon (Second one in from the left).

I checked the code and we only send the battery level as a percentage and the car's (partial) VIN to the server, so we don't handle miles or kilometres at all. I suspect it's a bug in the service due to the recent fix of the range value from Renault but it would be good to confirm that it's the same in their app.

**Comment by mjb1416** [comment]
Matt

I can confirm that the My Renault app is doing the same thing. I’d not thought of checking that. 

Regards

Mike

**Comment by paul-a-lucas** [comment]
This is still a "feature" for me (also broken in My Renault so it must be their APIs at fault).  Would it be possible to add a toggle in the settings for Zeddy to correct the value from the Renault APIs perhaps?
