### ISSUE TITLE
Car information does not change

### ISSUE THREAD

**Issue by CarolA87** [MattCheetham/zeddy-support#9]
I had an app ZE Services which did give me correct information about the state of the charging of my Zoe. I discarded it for Zeddy but it has never worked. I have tried deleting it and reinstalling but that has made no difference. My car will be 2 years old in October.

**Comment by Dave-09** [comment]
Do you have pictures of what you see?

**Comment by CarolA87** [comment]
No - it’s the format as shown on the app info but the figures are always the same.

**Comment by Dave-09** [comment]
Have you tried to refresh manually in Zeddy? If I understand correctly, you will see data, but it is not correct and it always remains the same? Do you see the correct registration number in Zeddy?

**Comment by CarolA87** [comment]
Yes, the data is always the same. The number plate is correct. By refreshing manually do you mean logging out and then on again? Which I have tried.

**Comment by Dave-09** [comment]
No, I mean you're running a PULL request. (Swipe your fingers down within Zeddy, you will see 'Last update'.

**Comment by CarolA87** [comment]
Ah, thanks - I’ve now tried that and it tells me it was last dated 10 months ago but it won’t refresh - the little wheel just keeps turning.

**Comment by MattCheetham** [comment]
Hi @CarolA87, the issues you are describing are common of either a stuck telematics control unit (TCU) in the car which is fixed by removing a fuse and putting it back or an expired subscription. 

The first step would be to check that your subscriptions are still active in the settings in the car. (Usually called something like Connected Service) and to remove and re-insert Fuse 31. Information on how to remove the fuse is found in this video: https://www.youtube.com/watch?v=P7rGuYRJhsM&t

**Comment by CarolA87** [comment]
Just to say removing the fuse was the answer and it also solved the connectivity with my new mobile phone!
Many thanks  - so much more helpful than Renault’s R Link service!
Btw the fuses are tiny aren’t they? It was unfortunately dropped as it was removed and it took a long time to fish it out from the back!

Best,
Carol

**Comment by MattCheetham** [comment]
@CarolA87 You're very welcome. They are indeed very fiddly and I think every Zoe owner has lost one or two down that gap!
